trigger:
- main

name: Deploy APIM Stack

variables:
  azureServiceConnection: 'Demo Account'
  resourceGroupName: 'rutzsco-apim-internal'
  location: 'eastus'
  environmentName: 'APIM-ESLZ'
  deploymentName: 'api-management-ESLZ'
  workloadName: 'Api-Management-ESLZ'
  eslzEnvironmentType: 'dev'
  CICDAgentType: 'azuredevops'
  appGatewayCertType: 'selfsigned'
  templateFile: 'reference-implementations/AppGW-IAPIM-Func/bicep/main.bicep'
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "using serviceconnection :" $(azureServiceConnection)
      az deployment sub create --location $(location) --name $(deploymentName) --template-file $(templateFile) --parameters workloadName=$(workloadName) environment=$(eslzEnvironmentType) CICDAgentType=$(CICDAgentType) accountName=rutzsco appGatewayCertType=$(appGatewayCertType) appGatewayFqdn='rutzscolabs.com' certificatePassword=TBD personalAccessToken=TBD vmPassword=$(vmPassword) vmUsername=developer 

      
      
